### ISSUE TITLE
need reference sandbox for community development, testing

### ISSUE THREAD

**Issue by isaacvetter** [fhircast/docs#1]
Implementer-driven standards are successful when an initial prototype can be rapidly developed in a few hours. Access to a legally unencumbered, online reference sandbox tremendously aids developers in rapidly creating prototypes.

To be successful FHIRcast needs a simple, usable sandbox.

Some industry sandboxes to perhaps emulate, include:
* https://sandbox.hspconsortium.org/
* http://sandbox.cds-hooks.org
* https://sandbox.smarthealthit.org/

Since there will always be more FHIRcast clients than servers, the most important functionality of a useful FHIRcast sandbox will be server emulation. A successful sandbox should:
1) Expose an unsecured FHIR Subscription endpoint at which a client can create new resource instances.
2) Provide a web user interface that allows a visitor to generate workflow events, e.g. a button the user can click to cause a "patient-open-chart" event to fire.
3) The ability to notify a subscribed app when an event occurred by POSTing a UserSession resource to the endpoint specified in the subscription resource instance.

**Comment by eitanbehar** [comment]
Thanks for bringing this up.  I think first priority would be having a sandbox server available to verify client implementations.

**Comment by isaacvetter** [comment]
closing in favor of duplicate issue #19.
