### ISSUE TITLE
Why are we avoiding MRN for patient Focus?

### ISSUE THREAD

**Issue by jeremysrichardson** [fhircast/docs#11]
MRN and Assigning Authority will always have to be looked up by any participating systems, unless they have seen the patient before and they cache the MRN.

**Comment by isaacvetter** [comment]
Is the (_elements)[https://www.hl7.org/fhir/search.html#elements] search param in use with includes, a workable approach?

**Comment by NiklasSvenzen** [comment]
I agree that we should include the most fundamental data items in the event notifications to avoid requiring to many round trips for at least the most basic use cases.

For the new WebSub approach perhaps we can use something like this:

"subject": [ {"identifier": "mrn1234", 
	              "https://fhir.hub.example.com/Patient/uyhlm9ls2tmuwuk"
                  },
                 {"identifier": "accno9876", 
	             "https://fhir.hub.example.com/Encounter/4aw1gs8f8r3yd2v"
                 }
	  ]

**Comment by isaacvetter** [comment]
Hey @jeremysrichardson , @NiklasSvenzen ,

I've got a proposed solution to this issue in PR #21. I want to keep FHIR as the actual content data model. While an approach like the one Niklas proposes: 
```
{
  "example": "5.5",
  "timestamp": "2018-01-08T01:37:05.14",
  "id": "q9v3jubddqt63n1",
  "event": {
    "hub.topic": "7jaa86kgdudewiaq0wtu",
    "hub.event": "open-patient-chart",
    "subject": {
      "patient": {
        "fullUrl": "http://hl7.org/fhir/Patient/ewUbXT9RWEbSj5wPEdgRaBw3",
        "identifier": [
          {
            "system": "urn:oid:1.2.840.114350",
            "value": "185444"
          },
          {
            "system": "urn:oid:1.2.840.114350.1.13.861.1.7.5.737384.27000",
            "value": "2667"
          }
        ]
      }
    }
  }
}
```

Is simple and exactly addresses this issue, it also takes us out of FHIR for the exchange of user session context.  Instead, I'm proposing that the Hub communicate context information as "subsetted" FHIR resources. The [\_elements](https://www.hl7.org/fhir/search.html#elements) query parameter in the FHIR spec causes a (compliant) FHIR server to return a resource with only the requested data elements (alonside any required data elements). Using this feature, it's reasonable for a FHIR server to send the subscriber a FHIR resource with only the FHIR id, the "business" identifiers and any other required fields. It would look like this:

```
{
  "timestamp": "2018-01-08T01:37:05.14",
  "id": "q9v3jubddqt63n1",
  "event": {
    "hub.topic": "7jaa86kgdudewiaq0wtu",
    "hub.event": "open-patient-chart",
    "context": [
      {
        "key": "patient",
        "resource": {
          "resourceType": "Patient",
          "id": "ewUbXT9RWEbSj5wPEdgRaBw3",
          "identifier": [
            {
              "system": "urn:oid:1.2.840.114350",
              "value": "185444"
            },
            {
              "system": "urn:oid:1.2.840.114350.1.13.861.1.7.5.737384.27000",
              "value": "2667"
            }
          ]
        }
      }
    ]
  }
}
```

This means that subscribers can use standard FHIR libraries to parse the content. Of course, not all FHIR servers will actually support this \_elements feature, so the subscriber should gracefully handle receiving the full FHIR resource as well.

Note that the [ImagingStudy](https://www.hl7.org/fhir/imagingstudy.html) resource does specify the accession number and DICOM uid as required. 

I'm kind of proud of this solution; what do y'all think?

Isaac

**Comment by jeremysrichardson** [comment]
**I really like the identifier list.**

Should the identifier have a type?  https://www.hl7.org/fhir/valueset-identifier-type.html

- I'd really like to know MRN, but I see a national health plan identifier in this [list](https://www.hl7.org/fhir/v2/0203/index.html#v2-0203-MR)...
- If these are MRNs, we also need an assigning authority (I can't see how that's modeled in FHIR)
- I'm ignorant of the existing spec on these matters, but there may be some additional structure necessary based on the type of identifier that may/may not include system.

You have two identifiers in the event.  How would a second identifier get added if the event comes from the EMR?

- IMHO: it wouldn't in the model above.  Why would a system add someone else's identifier?
- Again, MRN (and assigning authority) is probably key here for 99% of cases I've seen, but this brings up patient mapping as a potential service: which could be solved by an actor/system (probably an EMPI) that could publish those values.  This is probably more important for US markets b/c we generate unique MRNs for each system.

Take a 3+ way integration: If the event example above is generated from an application separate from the hub, how do we know where the patient resource exists?  --The patient's FHIR ID on the hub and the application publishing the event would be different.  Even if the hub doesn't have to be a FHIR server, we still don't know the application that published the event.

**Comment by isaacvetter** [comment]
Hey @jeremysrichardson ,

Great questions. 

* The above example is simply intended to be an example of a valid FHIR [Patient resource](https://www.hl7.org/fhir/patient.html) when the _elements parameter is in use. Here's the actual [FHIR Identifier data type](https://www.hl7.org/fhir/datatypes.html#identifier) that the above uses. Note that it does indeed include an assigner, as well as a few other id meta-data type fields. Here's an [example from the HAPI](http://hapi.fhir.org/baseDstu3/Patient//2072566?_elements=identifier) FHIR server.

* In practice, sometimes there can be multiple "mrns" defining a single patient within an EHR. Imo, the EHR implementation process naturally collects legacy system patient identifiers. To your first point, including the assigner and system and other id metadata is important.

Isaac
