### ISSUE TITLE
Should UserSession, Subscriptions be in FHIR?

### ISSUE THREAD

**Issue by isaacvetter** [fhircast/docs#13]
During discussion during the Jan HL7 FHIR Connectathon in New Orleans, Jenni Syed pointed out a few concerns with the current approach of using FHIR to represent the user's session. (Where a session is the active use of an application by a specific user on a specific device). Primarily two issues:

1) A typical enterprise application architecture separates an Identity (directory, authorization, etc) server from the resource server. The Identity or "session" server is primarily responsible for and further may be the only actor _aware_ of sessions. The resource server is not only logically distinct but may not even have reasonable access to session information, especially in federated identity scenarios. Requiring the resource server to expose session information is not only architecturally messy, but it may not even always be possible.

So, why not simply expose a second FHIR server which only supports Subscription and UserSession that runs on the Identity/session sever?

2) There's significant overhead in running an additional FHIR server - there may be US regulation or at least expectations that every EHR FHIR server exposes the CCDS, not just one or two resources for a specific use-case. Or, at the least, CapabilityStatement and other administrative features are a requirement.

Jenni's recommendation is to consider crafting simple, non-FHIR, RESTful APIs to run on the Identity server which wrap/reference resources on the single, CCDS-type FHIR server.

@daliboz - did I represent your thoughts, accurately?

**Comment by isaacvetter** [comment]
It's necessary to account for these enterprise application architecture design concerns.  What would be necessary to remove UserSession (and unfortunately therefore the subscription mechanism) from FHIR?

We'd need to define:
* a data model for a user's active session on a particular device
* a read method for the session
* a search method for the session
* a subscription data model
* a subscribe operation
* an unsubscribe operation
* subscription error handling
* a subscription notification data model
* a subscription data exchange model

We get a lot of this for free by using FHIR. @daliboz - Can we further explore ways to make it reasonable to use a dedicated "session" FHIR server on top of an Identity server?

**Comment by daliboz** [comment]
I don't even know if you would always want to run it on the identity server - but I think having the abstraction for the session management allows you to choose where this responsibility lies, based on your architecture. I think we should explore implementations that exist for multiple connectivity and identity workflows. We should also keep in mind that we're talking more about focus events on devices that session sign in and log out correct?

As to the things we lost - many of the Subscription channels are based on existing standards, we can build on those. Also, we probably don't need the SMS/email notification? There may be other simplifications we can make where the functionality didn't make sense for this specific use case? This is something else we should explore more.

**Comment by IntegratorBrad** [comment]
It's probably also interesting to explore the following; one could make an argument that "other" services that FHIR defines would also potentially live on non-core-FHIR servers. For example, a user session generally should be bound toward where auditing is occurring - https://www.hl7.org/fhir/auditevent.html - and, audit has some interesting "things" that relate toward these user sessions, such as location, policy, purpose, and entity.

There's also something to be said that we would force FHIR services onto applications that, otherwise, wouldn't even implement FHIR - e.g., if all the EMRs embraced FHIRcast, what of all the legacy PACS? However, the struggles out there in hospital ecosystems are real - every site is a custom integration, many of which are uneven - so, there's tertiary benefits possibly here.

**Comment by isaacvetter** [comment]
@daliboz , @WillMaethner and I talked through this issue this morning. Jenni's going to continue researching how her existing implementations work. 

I wanted to address some of the questions in this thread and also keep is up to date.
>We should also keep in mind that we're talking more about focus events on devices rather than just session sign in and log out correct?
Definitely. User login/logout, patient chart open/close/switch, imaging study open/close, additional focus changes are all in scope. Further, the "focus events" are really the more important than the user login/logout.

>we should explore implementations that exist for multiple connectivity and identity workflows. 

Ultimately, there's two pieces that matter:
1) Session discovery - how and where to expose session directory. Should this be FHIR?
In a modular enterprise application, session management is a service within the identity provider. The IdP/session management service doesn't interact with clinical data and doesn't typically use FHIR. A SMART launch of a synchronized app solves this problem by using the existing OAuth<->FHIR server connection. 

2) Focus change event communication across network - how and where to expose? 
Once the synchronized app knows a session identifier, should it communicate with the EHR via a centralized endpoint? Can/should the EHR's focus change API server reside on localhost?

**Comment by nwhatt** [comment]
@isaacvetter how is the UserSession different from an OpenID Connect token? I'm not trying to say they're the same, but you may want to do some digging there since SMART is leveraging OpenID Connect.

**Comment by jeremysrichardson** [comment]
> session management is a service within the identity provider.

> how is the UserSession different from an OpenID Connect token? I'm not trying to say they're the same,

I think the UserSession must be a resource (hopefully I'm using the right terminology), not an identity.  I think there are situations where other identities may have access to a UserSession, but may not be the user in the UserSession.

**Comment by jeremysrichardson** [comment]
> Focus change event communication across network - how and where to expose?
> Once the synchronized app knows a session identifier, should it communicate with the EHR via a centralized endpoint? 

I don't think we should say "EHR."  We should say FHIRCast Server.

> Can/should the EHR's focus change API server reside on localhost?
_I assume you mean Localhost relative to the client.  Giant assumption._
Can: Yes, it should be possible.  CCOW could exist with a local or remote server and it worked really well in both configurations.  I think adoption might have been easier if a local, client API/context store had been made available.
Should: No.  I don't think this should be proscriptive.  It should be able to be local to the client or remote.

**Comment by isaacvetter** [comment]
Hey everybody and especially @daliboz ,

I finally made enough time to re-jigger this specification to move it from FHIR Subscriptions and the controversial FHIR UserSession resource to a more generic webhook pattern based upon the [WebSub W3C RFC](https://www.w3.org/TR/websub/). There's still some obvious and important pieces missing (example: bidirectional communication is just a simple restful session POST, but needs to be fleshed out).

I'd like to aim to use this version of the spec for the May FHIR connectathon. I'm going to go through the currently open issues and close those that don't apply. Would you  mind reviewing PR #21 towards giving critical feedback?

Isaac

**Comment by isaacvetter** [comment]
Fixed in PR #21. Great work everybody!

Closing this issue.
