### ISSUE TITLE
How should stand-alone launch apps authenticate?

### ISSUE THREAD

**Issue by jeremysrichardson** [fhircast/docs#17]
I spoke with a few people to try to get my head around how authentication would work for stand-alone apps.  I spoke with Isaac, and he thought it might be more appropriate to use the back-end services model for SMART over OAuth2.

http://docs.smarthealthit.org/authorization/backend-services/

**Comment by IntegratorBrad** [comment]
This is an important but challenging topic.
*typically*, the EMR account is different than the PACS account is potentially different from the dictation account. It is "dangerous from patient confidentiality" for context to be shared with a rogue party, but linking them together is also challenging.

**Comment by isaacvetter** [comment]
Hey @jeremysrichardson ,

I think that this is closely related to #4 , see the resolution to that issue and the spec's [Launch Scenario's](http://fhircast.org/launch-scenarios/) page. 

I had initially tried to also fit Backend services into FHIRcast as a third launching mechanism, but got held up on [this conversation](https://github.com/smart-on-fhir/fhir-bulk-data-docs/issues/44). (tldr; backend services doesn't have a user, we necesssarily do).

I _think_ this resolves, this particular issue, will you re-open if you disagree?

Isaac
