### ISSUE TITLE
Create a "test" or demo capability

### ISSUE THREAD

**Issue by daliboz** [fhircast/docs#19]
It would be helpful to suggest that "sandboxes" (or possibly production) implementations provide a way to trigger a subscription for testing. We could actually do this by suggesting implementers provide a "test" button or UI to allow a consuming application to test their subscription endpoint. 

However, a more important tool may be something closer to what CDS Hooks has: https://sandbox.cds-hooks.org/

In speaking with the CDS group (@kpshek), it sounds like having that website has been one of the most important tools in helping people adopt CDS hooks. This wouldn't solve production testing use cases, but does help subscribed applications test their implementations and see what code they may need to write.

**Comment by daliboz** [comment]
CC @rettema

**Comment by ElliotSilver** [comment]
I see this as an operation that takes a Subscription (or at least the channel portion of a Subscription that immediately causes the Subscription to be sent to the channel.  The result of the operation is an ObservationOutcome that includes information about whether the server was able to connect via the channel. The operation parameter is not persisted.

**Comment by jeremysrichardson** [comment]
+1

**Comment by isaacvetter** [comment]
Hey Guys,

The amazing @lbergnehr and @NiklasSvenzen from Sectra created a .Net core FHIRcast sandbox application, here - https://github.com/fhircast/sandbox

Currently, you can download and run the application. We're looking at getting it published to the web soon.

Isaac
