### ISSUE TITLE
UserSession example user isn't formatted as a reference type

### ISSUE THREAD

**Issue by wmaethner** [fhircast/docs#2]
The current UserSession example's format for "user" seems incorrect. It currently looks like:
**"user": "Practitioner/prov123",**
but should be:
**"user": {
    "reference": "Practitioner/prov123"
}"**
based on the reference type definition ([http://hl7.org/fhir/references.html#Reference](url)).

The same is true for the references in the focus property.

**Comment by isaacvetter** [comment]
Hey Will,

This excellent point became irrelevant following our rewrite of the spec this spring.

Isaac
