### ISSUE TITLE
Current context after subscription (without an event)

### ISSUE THREAD

**Issue by mbellehumeur** [fhircast/docs#28]
After subscribing to patient or study level events, the subscriber may need to know what the current context is and not have to wait for an event to get the information.
Perhaps we could have either a "query context" mechanism or send a  "current context" event right after subscribing

**Comment by isaacvetter** [comment]
In conversation with Glenn Potter, Sagy Mintz, @jeremysrichardson during the FHIR connectathon this weekend, we talked through the importance of a subscribing app being able to query a hub for current context and, on Sunday, decided on this path forward:

## App requests current context
Outside of an event-driven notification from the Hub to the subscriber, a subscribing app can query the Hub's topic url to check the current context for the session represented by the topic. A subscriber may perform this query immediately upon launching. Event-driven context notifications should take precedence.

```
GET https://hub.example.com/7jaa86kgdudewiaq0wtu 
Host: hub
Authorization: Bearer i8hweunweunweofiwweoijewiwe
```

```
{
  "timestamp": "2018-01-08T01:40:05.14",
  "id": "wYXStHqxFQyHFELh",
  "event": {
    "hub.topic": "https://hub.example.com/7jaa86kgdudewiaq0wtu",
    "context": [
      {
        "key": "patient",
        "resource": {
          "resourceType": "Patient",
          "id": "798E4MyMcpCWHab9",
          "identifier": [
            {
              "system": "urn:oid:1.2.840.114350",
              "value": "1345687"
            },
            {
              "system": "urn:oid:1.2.840.114350.1.13.861.1.7.5.737384.27000",
              "value": "7539"
            }
          ]
        }
      }
    ]
  }
}
```
