### ISSUE TITLE
Sync fhircast.org and build.fhir.org

### ISSUE THREAD

**Issue by wmaethner** [fhircast/docs#3]
The UserSession resource appears to be defined slightly differently between fhircast.org and build.fhir.org. Those should ideally be the same. 

BONUS: It would be nice to have a link to [http://build.fhir.org/usersession](url) from fhircast.org

**Comment by isaacvetter** [comment]
Hey Will,

This issue and the UserSession resource went away this spring following our rewrite of the spec.

Closing this issue.

Isaac
