### ISSUE TITLE
Outsider question related to FHIRCast.org spec: how does my App find it's FHIR UserSession?

### ISSUE THREAD

**Issue by jeremysrichardson** [fhircast/docs#4]
When looking at FHIRCast.org, it was unclear to me how a subscribing client knows where a server lives.

From the primary use case, the FHIRCast server is always the launching server, and could pass the location to the FHIRCast server in the launch call.  If there are N apps in a hospital, each of them could have their own FHIRCast/FHIR Subscription w UserSession server.

In a stand-alone launch call, it's less clear.  If each app has its own UserSession, then they won't talk to each other.  Talking to Isaac (Connectahon 1/27), he thinks it's implementation configuration (Seems obvious, right?)  However, I think this is a key assumption that should be called out, and leads to the problem that the different apps need to share a common UserSession: a simple solution is a SINGLE pre-defined FHIRCast server to allow stand-alone apps to share context.

I think we should make this explicit for both launch types...

**Comment by IntegratorBrad** [comment]
How does it get done now? I think we could certainly leverage current practices in all of the custom implementations of this right now.

I guess there's also the possibility for "auto-discovery" mechanisms (e.g., the DNS records, those sorts of things), but practically, or as a version 1, practically people just manually set this value..?

It's certainly important to call out if we are thinking it's either 1) a single "UserSession" that is shared amongst participants or 2) a "synchronized set" of UserSessions across each stakeholder application. If there are more than two participants - then maybe the solution might want to take a turn to "conference" technologies like XMPP ..? (https://en.wikipedia.org/wiki/XMPP)

**Comment by isaacvetter** [comment]
Hey @jeremysrichardson ,

We finally wrote up, reviewed, approved and merged the content in this page: http://fhircast.org/launch-scenarios/ as part of PR #25. 

A session identifier is communicated as one of the SMART launch parameters. And the app can be launched using either SMART's so-called "EHR Launch" or the "Standalone launch". 

I _think_ that resolved this issue.

Isaac
