### ISSUE TITLE
FHIRCast Prototype with Websocket client connections

### ISSUE THREAD

**Issue by gkustas** [fhircast/docs#45]
I am currently implementing a prototype FHIRCast implementation that includes:

1. A FHIR Hub. 
2. A FHIRCast integration module for the Powerscribe360 Reporting solution (by Nuance)
3. A Test Client application (used to simulate other clients, such as PACS)

Items #1 and #3 are running, and item #2 is partially running. I'm hoping to have something ready for testing in a week or two.

At this point, I would like to share the technical specification details. Because this implementation supports Websockets, there are going to be several conformance issues that have been discussed in other issues on this forum. Particularly in how the FHIRCast(WebSub) subscription/publication model works with regards to callbacks.

My implementation proposes a solution that attempts to closely follow the FHIR and FHIRCast specifications for use with Radiology reporting context changes. The events supported by the hub include:

open-imaging-study
switch-imaging-study
close-imaging-study
user-logoff

I'm attaching a MS Word document which describes the implementation and specifications in more detail. I wold love to get feedback from all of you, particularly someone interested in implementing a FHIRCast client (like PACS).

There are several areas of the FHIR and FHIRCast specs that are unclear to me. Among them:
1.  For studies, what are the standards for specifying an accession number identifier (what is the system value?).
2. For patients, what are the standards for patient MRN, etc.?
3. Error handling - so many things to discuss eventually, but at this prototype stage I am going to defer implementation. Discussion would be helpful though at this time.
4. Like error handling, authentication needs to be discussed, but is being deferred from implementation.
5. Topics: I view the topic as an identifier for a user session. User Joe logs into PACS, and then into Powerscribe360 to dictate a report for the study.  The user session is defined as all of the software being used by user Joe. But if user Joe doesn't have identical user names on each of his software systems, what can be used to identify the user session (topic name)?

If anyone is interested, I can share source code, put our hub in the cloud, and perform unit testing with Powerscribe360.

[FHIR Websockets.docx](https://github.com/fhircast/docs/files/2590272/FHIR.Websockets.docx)

**Comment by mbellehumeur** [comment]
Hi @gkustas,
I have the same issue with the “session-id/hub.topic”.  In my mind, the hub has to resolve session assignment through some mechanism (same user id, if not  same hostname,..). 
Regarding the need for the client to listen on a socket, I had a different understanding.  To me, only the application servers needs to receive notification and they would take care to notify their clients with whatever is convenient for their app.  I tried to convey that in the JS sandbox (https://github.com/fhircast/sandbox.js).  
That said I am interested in your proposal of websockets directly to the hub and would like to prototype something to that effect.   Could we have a chat early this week?  I’m on Frankfurt time .  Thanks, Martin
