### ISSUE TITLE
Draft Use Case: Radiology: publish supporting data related to Patient/Exam context

### ISSUE THREAD

**Issue by jeremysrichardson** [fhircast/docs#8]
There are many use cases around publishing data during related to a Radiology reporting workflow

* Publishing measurements from PACS or other system to Reporting System for auto-population
* Publishing Imaging AI algorithm output for use in diagnosis or reporting

This seems analogous to a CDS-Hook card.

**Comment by IntegratorBrad** [comment]
This is great. There's many use cases of sharing Observations across user sessions. One thing we want to avoid is, "Radiologist reads a value from one system so it gets dictated into another system" !
